### ISSUE TITLE
Errors with OF 0.8.4

### ISSUE THREAD

**Issue by mateusk** [HalfdanJ/ofxStreamer#3]
Hi,

Thanks for this addon. But I am having no luck while trying to compile it using 0.8.4. Most of them are like the following:

/of_v0.8.4_osx_release/addons/ofxStreamer/src/ofxStreamerReceiver.cpp:265:12: Non-const lvalue reference to type 'ofPixels' (aka 'ofPixels_<unsigned char>') cannot bind to a temporary of type 'unsigned char *'

I guess this is because you used the latest master branch of OF, but is there anything I could change in order to work with 0.8.4?

**Comment by smukkejohan** [comment]
Yeah sorry about not keeping an 0.8.4 branch/tag around. I think this commit will work with 0.8.4 https://github.com/HalfdanJ/ofxStreamer/tree/6c036b7fb2abc750367b97ac21a990458f0402c3

**Comment by mateusk** [comment]
Well, I'm still getting errors... most of them of the like:

"/of_v0.8.4_osx_release/addons/ofxStreamer/src/ofxStreamerSender.h:66:11: No member named 'clock_t' in the global namespace"
"/of_v0.8.4_osx_release/addons/ofxStreamer/src/ofxStreamerSender.h:68:11: No member named 'tm' in the global namespace"
"/of_v0.8.4_osx_release/addons/ofxStreamer/src/ofxStreamerSender.h:70:11: No member named 'clock' in the global namespace"

And many others like these. It seems that there is some conflict with ffmpeg's "time.h" in libavutil, and the compiler's own "time.h". Any advice on this?

**Comment by mateusk** [comment]
Also, do you think this would work in Linux? I'm interested in streaming video from a Raspberry Pi (Debian - Raspbian) to an Apple computer.
